Nuevo flujo de modificar contraseña
tomasiturralde/bibliotecame-back pull request #80
Opened 2020-11-03 22:11 UTC by kuhamaven

## Description

Anteriormente existía un solo endpoint para la modificación del perfil de un usuario junto a su contraseña, haciendo que sea una experiencia incomoda y poco intuitiva para el usuario.
Para solucionar esto se separó dicho endpoint en dos:
-UpdateUser para permitir modificar telefono, nombre y apellido.
-UpdatePassword para modificar la contraseña (siempre que sea valida).
Ambos siguen verificando que efectivamente el usuario este logeado, y que la id del usuario a modificar coincidan con la del usuario logeado.
El UpdatePassword la encripta y guarda de forma correcta.

## ClubHouse Link

> https://app.clubhouse.io/bibliotecame/story/308/modificar-contrase%C3%B1a-nuevo-flujo

## Checklist
- [x] I've created and run successfully the related unit tests
- [x] I've run successfully every test in the repo
- [x] I've test the related endpoints with Postman
- [x] This pull request has 'sprint_x' as the base branch
- [x] This pull request has a descriptive title and description
- [x] I have merged the current sprint into my branch before pushing 
- [x] I've added the QA Leader as a reviewer

2020-11-08 14:06 UTC, LucasManza commented
Cambiar titulo -> Added new password update flow

2020-11-08 14:06 UTC, LucasManza commented
> Cambiar titulo -> Added new password update flow

Agregar dev reviewer

2020-11-08 15:30 UTC, rocioferreiro requested changes

2020-11-08 15:30 UTC, rocioferreiro commented on src/main/java/bibliotecame/back/User/UserController.java
> +        if(!password.getPassword().matches(passwordRegex)) return new ResponseEntity(new ErrorMessage("¡La contraseña debe contener solo letras y números, y al menos una de cada una!"), HttpStatus.BA
El error no esta describiendo el caso de una contraseña muy corta. Debería ser, por ejemplo, "La contraseña debe contener ambos, letras y números, y tener más de 6 caracteres"

2020-11-08 15:41 UTC, rocioferreiro commented
También me parece que estaría bueno que no te deje cambiar la contraseña a la misma que ya tenias. 
@LucasManza corroborar esto.

2020-11-08 17:29 UTC, kuhamaven commented on src/main/java/bibliotecame/back/User/UserController.java
> +        if(!password.getPassword().matches(passwordRegex)) return new ResponseEntity(new ErrorMessage("¡La contraseña debe contener solo letras y números, y al menos una de cada una!"), HttpStatus.BA
Corregido esto

2020-11-08 17:31 UTC, kuhamaven commented
@rocioferreiro Como tenes que agarrar la nueva que te llega, encriptarla y ahi compararla con la que ya tiene guardada en la db el usuario, creo que tardás más en hacer todo ese chequeo que en aprobarle la misma contraseña y listo

2020-11-08 17:51 UTC, rocioferreiro approved these changes
LGTM

2020-11-08 19:21 UTC, LucasManza commented on src/main/java/bibliotecame/back/User/UserController.java
> +    @PutMapping("user/{id}/updatepassword")
updatePassword

2020-11-08 19:21 UTC, LucasManza commented on src/main/java/bibliotecame/back/User/UserController.java
> +    public ResponseEntity updatePassword(@PathVariable Integer id, @RequestBody PasswordContainer password){
La funcionalidad es correcta pero acosto de la legibilidad.
Si es posible, limpiar el codigo para que queda mas legible. Hay 4 returns distintos if  y try catch mezclados

2020-11-08 20:04 UTC, LucasManza requested changes
Comentarios de review no fueron cargados

2020-11-10 13:58 UTC, LucasManza approved these changes

2020-11-10 13:58 UTC, merged